### ISSUE TITLE
Is Multivalent really used?

### ISSUE THREAD

**Issue by foolip** [izh1979/makepdf#3]
The README explains where to get Multivalent20091027.jar, but the makepdf script passes `--use-multivalent=false` to pdfsizeopt:

https://github.com/izh1979/makepdf/blob/4d4f3eb9cd64cfa221d94069bbd93683c9fc7d7a/makepdf#L33

Is it used anywhere else, or is Multivalent simply no longer a dependency of this project?

**Comment by izh1979** [comment]
It is an optional module. I've made a comparison (in README.md) and you can see that it is useful. But it could depend on the source document. Since it's not maintained anymore, I've made it off by default. But every user can check its effect on their documents.

**Comment by izh1979** [comment]
I wouldn't remove the submodule because it would be harder to enable it. Currently you can simply change --use-multivalent to true and it would be used.

(Also multivalent is written in Java and requires JRE to be set-up, although in modern Linux distros it's already there. And it increases the total time of document generation. So anybody should decide by themselves whether its effect worth using it.)

**Comment by foolip** [comment]
Is it enabled in the setup generating the HTML PDF?

**Comment by izh1979** [comment]
Wasn't, but I've enabled it now. (Don't remember why I turned it off.) It reduces the final file by 50 KB, but atakes about 2 extra minutes.

**Comment by foolip** [comment]
OK, if it's just 50 KB then I will leave it disabled in my work to make PDF generation part of html-build.

Maybe you can document how to enable Multivalent to close this issue?

**Comment by izh1979** [comment]
Added a couple of words about Multivalent installing: https://github.com/izh1979/makepdf/blob/master/README.md#multivalent

**Comment by foolip** [comment]
Thanks, closing this issue!
